-- ================================================================
-- SEEDS: 22 Arcanos Mayores — Rider-Waite-Smith
-- imagen_url: path relativo en Storage (bucket tarot-assets)
-- ================================================================

INSERT INTO tarot_cartas (mazo_id, nombre_es, nombre_en, arcano, numero, imagen_url, imagen_alt, significado_normal, significado_invertido, keywords) VALUES
('a1000000-0000-0000-0000-000000000001','El Loco','The Fool','mayor',0,'mazos/rws/mayor/00-el-loco.webp','El Loco — carta de tarot','Nuevos comienzos, espontaneidad, aventura, fe ciega, potencial sin explotar. Momento de dar el salto con confianza.','Imprudencia, ingenuidad peligrosa, riesgo sin calcular, irresponsabilidad.',ARRAY['comienzo','aventura','espontaneidad','libertad','potencial']),
('a1000000-0000-0000-0000-000000000001','El Mago','The Magician','mayor',1,'mazos/rws/mayor/01-el-mago.webp','El Mago — carta de tarot','Voluntad, habilidad, poder de manifestación, concentración, acción consciente. Tenés todas las herramientas necesarias.','Manipulación, talento desperdiciado, engaño, falta de foco.',ARRAY['manifestacion','voluntad','habilidad','poder','accion']),
('a1000000-0000-0000-0000-000000000001','La Sacerdotisa','The High Priestess','mayor',2,'mazos/rws/mayor/02-la-sacerdotisa.webp','La Sacerdotisa — carta de tarot','Intuición, misterio, conocimiento interior, paciencia, sabiduría subconsciente. Escuchá tu voz interna.','Secretos ocultos, desconexión intuitiva, información retenida.',ARRAY['intuicion','misterio','sabiduria','subconsciente','paciencia']),
('a1000000-0000-0000-0000-000000000001','La Emperatriz','The Empress','mayor',3,'mazos/rws/mayor/03-la-emperatriz.webp','La Emperatriz — carta de tarot','Abundancia, fertilidad, creatividad, naturaleza, maternidad, placer sensorial. Época de florecimiento.','Dependencia, bloqueo creativo, descuido, escasez.',ARRAY['abundancia','fertilidad','creatividad','naturaleza','maternidad']),
('a1000000-0000-0000-0000-000000000001','El Emperador','The Emperor','mayor',4,'mazos/rws/mayor/04-el-emperador.webp','El Emperador — carta de tarot','Autoridad, estructura, estabilidad, liderazgo, disciplina, poder terreno. Momento de establecer orden.','Rigidez, autoritarismo, control excesivo, abuso de poder.',ARRAY['autoridad','estructura','liderazgo','disciplina','orden']),
('a1000000-0000-0000-0000-000000000001','El Sumo Sacerdote','The Hierophant','mayor',5,'mazos/rws/mayor/05-el-sumo-sacerdote.webp','El Sumo Sacerdote — carta de tarot','Tradición, espiritualidad institucional, enseñanza, conformidad, guía espiritual.','Dogmatismo, rebelión, rigidez espiritual.',ARRAY['tradicion','espiritualidad','ensenanza','guia','conformidad']),
('a1000000-0000-0000-0000-000000000001','Los Enamorados','The Lovers','mayor',6,'mazos/rws/mayor/06-los-enamorados.webp','Los Enamorados — carta de tarot','Amor, elección, valores, alineación, relaciones significativas, unión. Elegir desde el corazón.','Desalineación de valores, mala decisión, conflicto interno.',ARRAY['amor','eleccion','valores','union','alineacion']),
('a1000000-0000-0000-0000-000000000001','El Carro','The Chariot','mayor',7,'mazos/rws/mayor/07-el-carro.webp','El Carro — carta de tarot','Victoria, control, determinación, disciplina, triunfo, avance poderoso. La voluntad lleva al éxito.','Falta de control, agresividad, derrota, arrogancia.',ARRAY['victoria','control','determinacion','triunfo','fuerza']),
('a1000000-0000-0000-0000-000000000001','La Fuerza','Strength','mayor',8,'mazos/rws/mayor/08-la-fuerza.webp','La Fuerza — carta de tarot','Valentía interior, paciencia, compasión, dominio suave, resiliencia. La fuerza viene del amor.','Inseguridad, debilidad, abuso de fuerza, falta de confianza.',ARRAY['valentia','paciencia','compasion','resiliencia','dominio']),
('a1000000-0000-0000-0000-000000000001','El Ermitaño','The Hermit','mayor',9,'mazos/rws/mayor/09-el-ermitano.webp','El Ermitaño — carta de tarot','Introspección, búsqueda interior, soledad elegida, guía, sabiduría. Encontrar la verdad en el silencio.','Aislamiento excesivo, rechazo a la guía, soledad no elegida.',ARRAY['introspección','sabiduria','silencio','busqueda','retiro']),
('a1000000-0000-0000-0000-000000000001','La Rueda de la Fortuna','Wheel of Fortune','mayor',10,'mazos/rws/mayor/10-la-rueda.webp','La Rueda de la Fortuna — carta de tarot','Ciclos, destino, cambio de suerte, karma, puntos de inflexión. Todo gira.','Mala suerte, resistencia al cambio, estancamiento.',ARRAY['ciclos','destino','cambio','karma','suerte']),
('a1000000-0000-0000-0000-000000000001','La Justicia','Justice','mayor',11,'mazos/rws/mayor/11-la-justicia.webp','La Justicia — carta de tarot','Equilibrio, verdad, ley, causa y efecto, equidad. Las acciones tienen consecuencias justas.','Injusticia, desequilibrio, deshonestidad, veredicto adverso.',ARRAY['justicia','equilibrio','verdad','ley','causa-efecto']),
('a1000000-0000-0000-0000-000000000001','El Colgado','The Hanged Man','mayor',12,'mazos/rws/mayor/12-el-colgado.webp','El Colgado — carta de tarot','Pausa, sacrificio voluntario, nueva perspectiva, suspensión. Soltar para ver con claridad.','Demoras innecesarias, martirio, resistencia al sacrificio.',ARRAY['pausa','sacrificio','perspectiva','suspension','soltar']),
('a1000000-0000-0000-0000-000000000001','La Muerte','Death','mayor',13,'mazos/rws/mayor/13-la-muerte.webp','La Muerte — carta de tarot','Transformación, final de ciclo, cambio inevitable, renovación. Algo termina para que nazca algo nuevo.','Resistencia al cambio, miedo al fin, estancamiento en lo viejo.',ARRAY['transformacion','final','cambio','renovacion','transicion']),
('a1000000-0000-0000-0000-000000000001','La Templanza','Temperance','mayor',14,'mazos/rws/mayor/14-la-templanza.webp','La Templanza — carta de tarot','Moderación, paciencia, equilibrio, sanación, flujo. Mezclar con sabiduría los opuestos.','Desequilibrio, excesos, impaciencia, falta de moderación.',ARRAY['moderacion','paciencia','equilibrio','sanacion','armonia']),
('a1000000-0000-0000-0000-000000000001','El Diablo','The Devil','mayor',15,'mazos/rws/mayor/15-el-diablo.webp','El Diablo — carta de tarot','Apego, materialismo, adicciones, sombra personal. Las cadenas muchas veces son propias.','Liberación de ataduras, reconocimiento de dependencias.',ARRAY['apego','sombra','dependencia','materialismo','liberacion']),
('a1000000-0000-0000-0000-000000000001','La Torre','The Tower','mayor',16,'mazos/rws/mayor/16-la-torre.webp','La Torre — carta de tarot','Ruptura repentina, revelación, caos liberador, destrucción de lo falso. Lo que cae fue construido sobre bases débiles.','Evitar el desastre, crisis contenida pero latente.',ARRAY['ruptura','revelacion','caos','destruccion','liberacion']),
('a1000000-0000-0000-0000-000000000001','La Estrella','The Star','mayor',17,'mazos/rws/mayor/17-la-estrella.webp','La Estrella — carta de tarot','Esperanza, inspiración, renovación, serenidad, fe, guía divina. Después de la tormenta llega la claridad.','Desesperanza, desconexión espiritual, falta de fe.',ARRAY['esperanza','inspiracion','fe','serenidad','renovacion']),
('a1000000-0000-0000-0000-000000000001','La Luna','The Moon','mayor',18,'mazos/rws/mayor/18-la-luna.webp','La Luna — carta de tarot','Ilusión, miedos, subconsciente, sueños, confusión, intuición profunda. Las cosas no son lo que parecen.','Liberación de miedos, claridad tras confusión, verdad que emerge.',ARRAY['ilusion','miedos','subconsciente','confusion','intuicion']),
('a1000000-0000-0000-0000-000000000001','El Sol','The Sun','mayor',19,'mazos/rws/mayor/19-el-sol.webp','El Sol — carta de tarot','Éxito, alegría, vitalidad, claridad, optimismo, abundancia. Período de florecimiento y celebración.','Bloqueo de energía vital, exceso de ego, optimismo ingenuo.',ARRAY['exito','alegria','vitalidad','claridad','optimismo']),
('a1000000-0000-0000-0000-000000000001','El Juicio','Judgement','mayor',20,'mazos/rws/mayor/20-el-juicio.webp','El Juicio — carta de tarot','Despertar, transformación, llamado interno, redención, renacimiento. Momento de responder al llamado del alma.','Autocrítica excesiva, negación del llamado, juicio severo.',ARRAY['despertar','renacimiento','llamado','transformacion','redencion']),
('a1000000-0000-0000-0000-000000000001','El Mundo','The World','mayor',21,'mazos/rws/mayor/21-el-mundo.webp','El Mundo — carta de tarot','Completitud, logro, integración, viaje completado, plenitud. Un ciclo culmina con éxito y satisfacción.','Ciclo incompleto, falta de cierre, sensación de incompletitud.',ARRAY['completitud','logro','plenitud','integracion','celebracion']);
