-- ================================================================
-- SEEDS: 56 Arcanos Menores — Rider-Waite-Smith
-- 4 palos x 14 cartas = 56
-- ================================================================

INSERT INTO tarot_cartas (mazo_id, nombre_es, nombre_en, arcano, numero, palo, carta_corte, imagen_url, imagen_alt, significado_normal, significado_invertido, keywords) VALUES

-- BASTOS (Fuego / Acción / Creatividad)
('a1000000-0000-0000-0000-000000000001','As de Bastos','Ace of Wands','menor',1,'bastos',null,'mazos/rws/menor/bastos/01-as.webp','As de Bastos','Inspiración, nuevo proyecto, energía creativa, potencial puro, oportunidad de acción.','Demoras, bloqueo creativo, proyectos que no arrancan.',ARRAY['inspiracion','comienzo','creatividad','accion','potencial']),
('a1000000-0000-0000-0000-000000000001','Dos de Bastos','Two of Wands','menor',2,'bastos',null,'mazos/rws/menor/bastos/02-dos.webp','Dos de Bastos','Planificación, visión futura, decisión, expansión, exploración de posibilidades.','Miedo a lo desconocido, falta de planificación, planes que no avanzan.',ARRAY['planificacion','vision','decision','expansion','futuro']),
('a1000000-0000-0000-0000-000000000001','Tres de Bastos','Three of Wands','menor',3,'bastos',null,'mazos/rws/menor/bastos/03-tres.webp','Tres de Bastos','Expansión, resultados que llegan, proyectos en marcha, liderazgo, mirada al horizonte.','Demoras inesperadas, obstáculos en el avance.',ARRAY['expansion','resultados','liderazgo','avance','horizonte']),
('a1000000-0000-0000-0000-000000000001','Cuatro de Bastos','Four of Wands','menor',4,'bastos',null,'mazos/rws/menor/bastos/04-cuatro.webp','Cuatro de Bastos','Celebración, estabilidad, hogar, comunidad, logro, alegría compartida.','Tensión en el hogar, celebración postergada.',ARRAY['celebracion','hogar','estabilidad','alegria','comunidad']),
('a1000000-0000-0000-0000-000000000001','Cinco de Bastos','Five of Wands','menor',5,'bastos',null,'mazos/rws/menor/bastos/05-cinco.webp','Cinco de Bastos','Conflicto, competencia, caos creativo, desafíos, tensión que impulsa.','Conflicto resuelto, evitar confrontación, acuerdos.',ARRAY['conflicto','competencia','desafio','tension','caos']),
('a1000000-0000-0000-0000-000000000001','Seis de Bastos','Six of Wands','menor',6,'bastos',null,'mazos/rws/menor/bastos/06-seis.webp','Seis de Bastos','Victoria, reconocimiento, éxito público, confianza, liderazgo celebrado.','Ego inflado, falta de reconocimiento, victoria sin celebración.',ARRAY['victoria','reconocimiento','exito','confianza','liderazgo']),
('a1000000-0000-0000-0000-000000000001','Siete de Bastos','Seven of Wands','menor',7,'bastos',null,'mazos/rws/menor/bastos/07-siete.webp','Siete de Bastos','Defensa, perseverancia, mantener posición, valentía ante la adversidad.','Agotamiento, rendirse ante la presión, perder terreno.',ARRAY['defensa','perseverancia','valentia','posicion','resistencia']),
('a1000000-0000-0000-0000-000000000001','Ocho de Bastos','Eight of Wands','menor',8,'bastos',null,'mazos/rws/menor/bastos/08-ocho.webp','Ocho de Bastos','Velocidad, movimiento rápido, comunicación fluida, noticias que llegan, momentum.','Demoras, frustración, mensajes retrasados.',ARRAY['velocidad','movimiento','comunicacion','noticias','rapidez']),
('a1000000-0000-0000-0000-000000000001','Nueve de Bastos','Nine of Wands','menor',9,'bastos',null,'mazos/rws/menor/bastos/09-nueve.webp','Nueve de Bastos','Resistencia, perseverancia final, guardia alta, casi en la meta, resiliencia.','Agotamiento extremo, paranoia, rendirse casi al final.',ARRAY['resistencia','perseverancia','resiliencia','guardia','final']),
('a1000000-0000-0000-0000-000000000001','Diez de Bastos','Ten of Wands','menor',10,'bastos',null,'mazos/rws/menor/bastos/10-diez.webp','Diez de Bastos','Carga pesada, responsabilidad excesiva, llegada al final con esfuerzo, sobrecarga.','Delegación necesaria, soltar cargas, aligeramiento.',ARRAY['carga','responsabilidad','esfuerzo','sobrecarga','meta']),
('a1000000-0000-0000-0000-000000000001','Paje de Bastos','Page of Wands','menor',null,'bastos','paje','mazos/rws/menor/bastos/11-paje.webp','Paje de Bastos','Exploración, entusiasmo juvenil, mensajes de acción, energía nueva, curiosidad.','Impulsividad, proyectos sin terminar, noticias tardías.',ARRAY['exploracion','entusiasmo','curiosidad','mensaje','energia']),
('a1000000-0000-0000-0000-000000000001','Caballero de Bastos','Knight of Wands','menor',null,'bastos','caballero','mazos/rws/menor/bastos/12-caballero.webp','Caballero de Bastos','Aventura, acción impulsiva, energía apasionada, cambio rápido, valentía.','Imprudencia, agresividad, energía mal dirigida.',ARRAY['aventura','pasion','impulso','accion','cambio']),
('a1000000-0000-0000-0000-000000000001','Reina de Bastos','Queen of Wands','menor',null,'bastos','reina','mazos/rws/menor/bastos/13-reina.webp','Reina de Bastos','Carisma, independencia, confianza, pasión, liderazgo femenino, energía solar.','Egocentrismo, celos, agotamiento de energía.',ARRAY['carisma','independencia','confianza','pasion','liderazgo']),
('a1000000-0000-0000-0000-000000000001','Rey de Bastos','King of Wands','menor',null,'bastos','rey','mazos/rws/menor/bastos/14-rey.webp','Rey de Bastos','Liderazgo visionario, emprendimiento, autoridad apasionada, maestría creativa.','Impulsividad sin dirección, tiranía, arrogancia.',ARRAY['liderazgo','vision','emprendimiento','autoridad','maestria']),

-- COPAS (Agua / Emociones / Relaciones)
('a1000000-0000-0000-0000-000000000001','As de Copas','Ace of Cups','menor',1,'copas',null,'mazos/rws/menor/copas/01-as.webp','As de Copas','Amor nuevo, desborde emocional, intuición, ofrenda del corazón, nueva relación.','Bloqueo emocional, amor reprimido, corazón cerrado.',ARRAY['amor','emocion','intuicion','corazon','nuevo']),
('a1000000-0000-0000-0000-000000000001','Dos de Copas','Two of Cups','menor',2,'copas',null,'mazos/rws/menor/copas/02-dos.webp','Dos de Copas','Unión, asociación, amor mutuo, atracción, vínculo profundo, conexión romántica.','Ruptura, desequilibrio en la relación, malentendidos.',ARRAY['union','amor','conexion','asociacion','vinculo']),
('a1000000-0000-0000-0000-000000000001','Tres de Copas','Three of Cups','menor',3,'copas',null,'mazos/rws/menor/copas/03-tres.webp','Tres de Copas','Celebración, amistad, comunidad, alegría compartida, festejo, abundancia emocional.','Excesos, chismes, aislamiento, celebración exagerada.',ARRAY['celebracion','amistad','comunidad','alegria','festejo']),
('a1000000-0000-0000-0000-000000000001','Cuatro de Copas','Four of Cups','menor',4,'copas',null,'mazos/rws/menor/copas/04-cuatro.webp','Cuatro de Copas','Apatía, contemplación, oportunidad ignorada, descontento, introspección emocional.','Salir del estancamiento, aceptar nuevas oportunidades.',ARRAY['apatia','contemplacion','descontento','oportunidad','introspección']),
('a1000000-0000-0000-0000-000000000001','Cinco de Copas','Five of Cups','menor',5,'copas',null,'mazos/rws/menor/copas/05-cinco.webp','Cinco de Copas','Pérdida, duelo, decepción, enfoque en lo negativo. Aún quedan copas en pie.','Aceptación, recuperación emocional, mirar hacia adelante.',ARRAY['perdida','duelo','decepcion','lamento','superacion']),
('a1000000-0000-0000-0000-000000000001','Seis de Copas','Six of Cups','menor',6,'copas',null,'mazos/rws/menor/copas/06-seis.webp','Seis de Copas','Nostalgia, infancia, inocencia, recuerdos, regalos del pasado, pureza emocional.','Vivir en el pasado, idealización, incapacidad de soltar.',ARRAY['nostalgia','infancia','recuerdos','inocencia','pasado']),
('a1000000-0000-0000-0000-000000000001','Siete de Copas','Seven of Cups','menor',7,'copas',null,'mazos/rws/menor/copas/07-siete.webp','Siete de Copas','Ilusión, fantasía, múltiples opciones, confusión, sueños vs realidad.','Claridad tras la confusión, decisión tomada.',ARRAY['ilusion','fantasia','confusion','opciones','deseos']),
('a1000000-0000-0000-0000-000000000001','Ocho de Copas','Eight of Cups','menor',8,'copas',null,'mazos/rws/menor/copas/08-ocho.webp','Ocho de Copas','Abandono, búsqueda espiritual, dejar atrás lo conocido, transición.','Miedo a abandonar, volver a lo conocido, apego.',ARRAY['abandono','busqueda','transicion','dejar','espiritual']),
('a1000000-0000-0000-0000-000000000001','Nueve de Copas','Nine of Cups','menor',9,'copas',null,'mazos/rws/menor/copas/09-nueve.webp','Nueve de Copas','Satisfacción, deseo cumplido, bienestar, placer, gratitud. La carta del deseo.','Autocomplacencia, deseos superficiales, satisfacción vacía.',ARRAY['satisfaccion','deseo','bienestar','placer','gratitud']),
('a1000000-0000-0000-0000-000000000001','Diez de Copas','Ten of Cups','menor',10,'copas',null,'mazos/rws/menor/copas/10-diez.webp','Diez de Copas','Felicidad familiar, armonía, plenitud emocional, hogar, amor duradero, bendición.','Ruptura familiar, armonía perturbada, felicidad condicionada.',ARRAY['felicidad','familia','armonia','plenitud','hogar']),
('a1000000-0000-0000-0000-000000000001','Paje de Copas','Page of Cups','menor',null,'copas','paje','mazos/rws/menor/copas/11-paje.webp','Paje de Copas','Creatividad emocional, intuición naciente, mensaje afectivo, sensibilidad, sorpresas.','Ingenuidad emocional, inmadurez sentimental.',ARRAY['creatividad','intuicion','sensibilidad','mensaje','sorpresa']),
('a1000000-0000-0000-0000-000000000001','Caballero de Copas','Knight of Cups','menor',null,'copas','caballero','mazos/rws/menor/copas/12-caballero.webp','Caballero de Copas','Romance, propuesta, idealismo, encanto, seguir el corazón, oferta emocional.','Idealismo excesivo, decepción romántica, propuesta vacía.',ARRAY['romance','propuesta','idealismo','encanto','corazon']),
('a1000000-0000-0000-0000-000000000001','Reina de Copas','Queen of Cups','menor',null,'copas','reina','mazos/rws/menor/copas/13-reina.webp','Reina de Copas','Compasión, intuición madura, empatía, cuidado emocional, sabiduría del corazón.','Codependencia, absorción emocional, falta de límites.',ARRAY['compasion','intuicion','empatia','cuidado','sabiduria']),
('a1000000-0000-0000-0000-000000000001','Rey de Copas','King of Cups','menor',null,'copas','rey','mazos/rws/menor/copas/14-rey.webp','Rey de Copas','Equilibrio emocional, sabiduría afectiva, diplomacia, madurez, liderazgo compasivo.','Represión emocional, manipulación, desequilibrio afectivo.',ARRAY['equilibrio','sabiduria','diplomacia','madurez','liderazgo']),

-- ESPADAS (Aire / Mente / Conflicto)
('a1000000-0000-0000-0000-000000000001','As de Espadas','Ace of Swords','menor',1,'espadas',null,'mazos/rws/menor/espadas/01-as.webp','As de Espadas','Claridad mental, verdad, breakthrough, nueva idea poderosa, corte con lo que no sirve.','Confusión, verdad dolorosa, bloqueo mental.',ARRAY['claridad','verdad','mente','idea','corte']),
('a1000000-0000-0000-0000-000000000001','Dos de Espadas','Two of Swords','menor',2,'espadas',null,'mazos/rws/menor/espadas/02-dos.webp','Dos de Espadas','Indecisión, bloqueo, equilibrio tenso, evitar la verdad, dilema sin resolver.','Decisión tomada, información que llega, fin del bloqueo.',ARRAY['indecision','bloqueo','dilema','equilibrio','evitar']),
('a1000000-0000-0000-0000-000000000001','Tres de Espadas','Three of Swords','menor',3,'espadas',null,'mazos/rws/menor/espadas/03-tres.webp','Tres de Espadas','Dolor, pena, pérdida, traición, corazón herido, separación, llanto necesario.','Recuperación del dolor, proceso de sanación, perdonar.',ARRAY['dolor','pena','perdida','traicion','separacion']),
('a1000000-0000-0000-0000-000000000001','Cuatro de Espadas','Four of Swords','menor',4,'espadas',null,'mazos/rws/menor/espadas/04-cuatro.webp','Cuatro de Espadas','Descanso, recuperación, retiro temporal, pausa necesaria, contemplación sanadora.','Agotamiento ignorado, vuelta prematura a la acción.',ARRAY['descanso','recuperacion','pausa','retiro','sanacion']),
('a1000000-0000-0000-0000-000000000001','Cinco de Espadas','Five of Swords','menor',5,'espadas',null,'mazos/rws/menor/espadas/05-cinco.webp','Cinco de Espadas','Conflicto, derrota, victoria vacía, deshonra, tensión, rivalidad.','Reconciliación posible, dejar ir el conflicto.',ARRAY['conflicto','derrota','rivalidad','tension','deshonra']),
('a1000000-0000-0000-0000-000000000001','Seis de Espadas','Six of Swords','menor',6,'espadas',null,'mazos/rws/menor/espadas/06-seis.webp','Seis de Espadas','Transición, alejarse del conflicto, viaje, calma tras la tormenta, avance tranquilo.','Resistencia al cambio, estancamiento, regreso a lo difícil.',ARRAY['transicion','viaje','calma','alejarse','avance']),
('a1000000-0000-0000-0000-000000000001','Siete de Espadas','Seven of Swords','menor',7,'espadas',null,'mazos/rws/menor/espadas/07-siete.webp','Siete de Espadas','Estrategia, engaño, actuar solo, evitar conflicto, astucia, secreto.','Confesión, verdad que sale a la luz, fin del engaño.',ARRAY['estrategia','engano','astucia','secreto','solo']),
('a1000000-0000-0000-0000-000000000001','Ocho de Espadas','Eight of Swords','menor',8,'espadas',null,'mazos/rws/menor/espadas/08-ocho.webp','Ocho de Espadas','Trampa mental, restricción percibida, victimismo, limitación autoimpuesta.','Liberación mental, ver más allá de los límites.',ARRAY['trampa','restriccion','victimismo','limitacion','mental']),
('a1000000-0000-0000-0000-000000000001','Nueve de Espadas','Nine of Swords','menor',9,'espadas',null,'mazos/rws/menor/espadas/09-nueve.webp','Nueve de Espadas','Ansiedad, pesadillas, pensamiento catastrófico, insomnio, miedo nocturno.','Fin de la ansiedad, esperanza que regresa, perspectiva más sana.',ARRAY['ansiedad','miedo','pesadilla','insomnio','catastrofe']),
('a1000000-0000-0000-0000-000000000001','Diez de Espadas','Ten of Swords','menor',10,'espadas',null,'mazos/rws/menor/espadas/10-diez.webp','Diez de Espadas','Final doloroso, traición, crisis inevitable, derrota total pero fin de ciclo.','Recuperación, el peor ya pasó, supervivencia, resurgir.',ARRAY['final','traicion','crisis','derrota','cierre']),
('a1000000-0000-0000-0000-000000000001','Paje de Espadas','Page of Swords','menor',null,'espadas','paje','mazos/rws/menor/espadas/11-paje.webp','Paje de Espadas','Curiosidad intelectual, vigilancia, mensaje directo, pensamiento ágil, alerta.','Chismes, pensamiento apresurado, información incorrecta.',ARRAY['curiosidad','vigilancia','mensaje','inteligencia','alerta']),
('a1000000-0000-0000-0000-000000000001','Caballero de Espadas','Knight of Swords','menor',null,'espadas','caballero','mazos/rws/menor/espadas/12-caballero.webp','Caballero de Espadas','Acción directa, ambición, velocidad de pensamiento, determinación, avance rápido.','Impulsividad destructiva, arrogancia intelectual.',ARRAY['accion','ambicion','velocidad','determinacion','directo']),
('a1000000-0000-0000-0000-000000000001','Reina de Espadas','Queen of Swords','menor',null,'espadas','reina','mazos/rws/menor/espadas/13-reina.webp','Reina de Espadas','Claridad, independencia, intelecto agudo, honestidad directa, perspectiva clara.','Frialdad excesiva, crueldad verbal, amargura.',ARRAY['claridad','independencia','intelecto','honestidad','perspectiva']),
('a1000000-0000-0000-0000-000000000001','Rey de Espadas','King of Swords','menor',null,'espadas','rey','mazos/rws/menor/espadas/14-rey.webp','Rey de Espadas','Autoridad intelectual, lógica, verdad, liderazgo analítico, mente maestra.','Tiranía mental, crueldad fría, manipulación intelectual.',ARRAY['autoridad','logica','verdad','analisis','liderazgo']),

-- OROS (Tierra / Materia / Recursos)
('a1000000-0000-0000-0000-000000000001','As de Oros','Ace of Pentacles','menor',1,'oros',null,'mazos/rws/menor/oros/01-as.webp','As de Oros','Oportunidad material, nuevo recurso, prosperidad naciente, inicio concreto, abundancia.','Oportunidad perdida, codicia, mal manejo del dinero.',ARRAY['oportunidad','prosperidad','recurso','abundancia','material']),
('a1000000-0000-0000-0000-000000000001','Dos de Oros','Two of Pentacles','menor',2,'oros',null,'mazos/rws/menor/oros/02-dos.webp','Dos de Oros','Equilibrio, malabarismo, adaptación, gestión de recursos, flexibilidad ante cambios.','Desequilibrio financiero, estrés por gestionar demasiado.',ARRAY['equilibrio','adaptacion','gestion','flexibilidad','malabarismo']),
('a1000000-0000-0000-0000-000000000001','Tres de Oros','Three of Pentacles','menor',3,'oros',null,'mazos/rws/menor/oros/03-tres.webp','Tres de Oros','Trabajo en equipo, colaboración, maestría en construcción, planificación conjunta.','Falta de colaboración, trabajo mediocre, desorganización.',ARRAY['trabajo','colaboracion','maestria','construccion','equipo']),
('a1000000-0000-0000-0000-000000000001','Cuatro de Oros','Four of Pentacles','menor',4,'oros',null,'mazos/rws/menor/oros/04-cuatro.webp','Cuatro de Oros','Seguridad, ahorro, control, apego al dinero, conservadurismo, protección de recursos.','Avaricia, apego excesivo, miedo a perder, bloqueo.',ARRAY['seguridad','ahorro','control','apego','proteccion']),
('a1000000-0000-0000-0000-000000000001','Cinco de Oros','Five of Pentacles','menor',5,'oros',null,'mazos/rws/menor/oros/05-cinco.webp','Cinco de Oros','Dificultad económica, exclusión, carencia, pobreza temporal, buscar ayuda.','Mejora financiera, fin de la escasez, apoyo que llega.',ARRAY['dificultad','carencia','exclusion','escasez','ayuda']),
('a1000000-0000-0000-0000-000000000001','Seis de Oros','Six of Pentacles','menor',6,'oros',null,'mazos/rws/menor/oros/06-seis.webp','Seis de Oros','Generosidad, dar y recibir, equilibrio económico, filantropía, recompensa justa.','Desequilibrio en el dar, deuda, generosidad condicionada.',ARRAY['generosidad','dar','recibir','equilibrio','recompensa']),
('a1000000-0000-0000-0000-000000000001','Siete de Oros','Seven of Pentacles','menor',7,'oros',null,'mazos/rws/menor/oros/07-siete.webp','Siete de Oros','Paciencia, evaluación del progreso, inversión a largo plazo, espera de resultados.','Impaciencia, trabajo sin retorno, frustración por resultados lentos.',ARRAY['paciencia','evaluacion','inversion','progreso','espera']),
('a1000000-0000-0000-0000-000000000001','Ocho de Oros','Eight of Pentacles','menor',8,'oros',null,'mazos/rws/menor/oros/08-ocho.webp','Ocho de Oros','Dedicación, aprendizaje, maestría, trabajo meticuloso, perfeccionamiento, foco.','Trabajo sin pasión, perfeccionismo bloqueante.',ARRAY['dedicacion','aprendizaje','maestria','trabajo','perfeccion']),
('a1000000-0000-0000-0000-000000000001','Nueve de Oros','Nine of Pentacles','menor',9,'oros',null,'mazos/rws/menor/oros/09-nueve.webp','Nueve de Oros','Independencia, abundancia ganada, lujo, autosuficiencia, éxito material, refinamiento.','Dependencia financiera, trabajo sin frutos, riqueza vacía.',ARRAY['independencia','abundancia','autosuficiencia','exito','lujo']),
('a1000000-0000-0000-0000-000000000001','Diez de Oros','Ten of Pentacles','menor',10,'oros',null,'mazos/rws/menor/oros/10-diez.webp','Diez de Oros','Legado, herencia, riqueza familiar, estabilidad multigeneracional, plenitud material.','Inestabilidad familiar, pérdida de herencia, riqueza sin significado.',ARRAY['legado','herencia','familia','riqueza','estabilidad']),
('a1000000-0000-0000-0000-000000000001','Paje de Oros','Page of Pentacles','menor',null,'oros','paje','mazos/rws/menor/oros/11-paje.webp','Paje de Oros','Ambición práctica, aprendizaje material, nuevo proyecto concreto, estudio, oportunidad.','Falta de foco, sueños sin acción, aprendizaje lento.',ARRAY['ambicion','aprendizaje','practica','proyecto','oportunidad']),
('a1000000-0000-0000-0000-000000000001','Caballero de Oros','Knight of Pentacles','menor',null,'oros','caballero','mazos/rws/menor/oros/12-caballero.webp','Caballero de Oros','Metodología, trabajo constante, confiabilidad, paciencia, avance lento pero seguro.','Rutina bloqueante, terquedad, falta de flexibilidad.',ARRAY['metodologia','constancia','confiabilidad','paciencia','seguro']),
('a1000000-0000-0000-0000-000000000001','Reina de Oros','Queen of Pentacles','menor',null,'oros','reina','mazos/rws/menor/oros/13-reina.webp','Reina de Oros','Abundancia práctica, cuidado del hogar, seguridad material, nutrición, equilibrio.','Dependencia material, descuido del hogar, desequilibrio financiero.',ARRAY['abundancia','practica','hogar','seguridad','cuidado']),
('a1000000-0000-0000-0000-000000000001','Rey de Oros','King of Pentacles','menor',null,'oros','rey','mazos/rws/menor/oros/14-rey.webp','Rey de Oros','Éxito material, liderazgo empresarial, abundancia establecida, seguridad, maestría financiera.','Materialismo excesivo, corrupción, mal manejo del éxito.',ARRAY['exito','empresa','abundancia','seguridad','liderazgo']);
